# Toy data characteristics
n_data: 1000 # Number of data points
noise: 0.01 # Noise in the data

# Algorithms characteristics
lr: 0.01 # Positive
batch_size: 32 # Positive int > n_data
epochs: 100 # Positive int
width: 30 # The width of the perceptron : Postive int

# Report directory and name
report_directory: "" # A path 
# (if leaved empty it will create a report folder at the root repo)
# (Do not forget to replace windows '\' by '/')
report_name: "" # "Name.html" 
# (if leaved empty the report will be named Toy_report.html)